[project]
name = "buurtkompas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "PaneledBus122", email = "sjlim122@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[project.scripts]
buurtkompas = "buurtkompas:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
