[project]
name = "buurtkompas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "PaneledBus122", email = "sjlim122@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.4",
    "dbt-postgres>=1.11.0",
    "geoalchemy2>=0.20.0",
    "geopandas>=1.1.4",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.13",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
buurtkompas = "buurtkompas:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
